### ISSUE TITLE
Bunch of Laravel-related 🔥 snippets

### ISSUE THREAD

**Issue by wojciechgabrys** [Reached/tweetsnippet#7]
Hi @Reached , I've just now stumbled upon https://tweetsnippet.com/ and wanted to congratulate you on a job well done!

I've been collecting links to 🔥 tweets (mostly Laravel related) for some time now and thought that you might make use of them.

Please have a look at https://github.com/wojciechgabrys/laravel.tips – most of them are tagged (but I need to go through the "Conflicted" files and remove duplicates)

**Comment by Reached** [comment]
Hi @wojciechgabrys, this is amazing, thank you very much!

Great job on collection those tips, I know how much time it takes 💪 💪

**Comment by wojciechgabrys** [comment]
Thanks for the kind words - I'm glad I could help.

I did it using iOS automation (Shortcuts.app + Bear.app) - if you'd like, I can share my workflow.

**Comment by Reached** [comment]
That would be cool! :)
